os: osx
osx_image: xcode11.3
language: swift

branches:
  only:
    - master

stages:
  - name: lint
    if: branch = master

jobs:
  include:
      - stage: lint
        install: gem install cocoapods -v '~> 1.7.5'
        script:
          - pod lib lint --allow-warnings
