os: osx
osx_image: xcode11.3
language: swift

branches:
  only:
    - master

stages:
  - name: lint
    if: branch = master
  - name: test
    if: branch = master

jobs:
  include:
      - stage: lint
        install: gem install cocoapods -v '~> 1.7.5'
        script: pod lib lint --project-directory=ActivityIndicatorManager

      - stage: test
        script:
          - pod install --project-directory=ActivityIndicatorManagerDemo
          - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace ActivityIndicatorManagerDemo/ActivityIndicatorManagerDemo -scheme ActivityIndicatorManagerDemo -destination 'platform=iOS Simulator,OS=13.3,name=iPhone SE' ONLY_ACTIVE_ARCH=NO | xcpretty