# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ActivityIndicatorManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ActivityIndicatorManager

  target 'ActivityIndicatorManagerTests' do
    # Pods for testing
  end

end
